# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63448171bcdae0e36066618fa372afdab0fc35e9a8d681977d6c17c4fa4b243f1d7ee8cf0fe14b9dffffcf8aa54cff4ad8bba822d27b5f686dac6c99027b3bca

test:
  secret_key_base: 83a074fc09dba8ff66201bc69828dd1ca0cf48580b15b71ac795db9af1f8f5b420507a41218dca327bbc317d588bff1ba6ff33a51303e8759fba96c4d4d704f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
